module.exports = {
  StartBlock: 6627917, // the Contract creation block for the uniswap factory https://etherscan.io/tx/0xc1b2646d0ad4a3a151ebdaaa7ef72e3ab1aa13aa49d0b7a3ca020f5ee7b1b010
  FactoryAddress: '0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95',
  FactoryABI: [
    {
      name: 'NewExchange',
      inputs: [
        { type: 'address', name: 'token', indexed: true },
        { type: 'address', name: 'exchange', indexed: true },
      ],
      anonymous: false,
      type: 'event',
    },
    {
      name: 'initializeFactory',
      outputs: [],
      inputs: [{ type: 'address', name: 'template' }],
      constant: false,
      payable: false,
      type: 'function',
      gas: 35725,
    },
    {
      name: 'createExchange',
      outputs: [{ type: 'address', name: 'out' }],
      inputs: [{ type: 'address', name: 'token' }],
      constant: false,
      payable: false,
      type: 'function',
      gas: 187911,
    },
    {
      name: 'getExchange',
      outputs: [{ type: 'address', name: 'out' }],
      inputs: [{ type: 'address', name: 'token' }],
      constant: true,
      payable: false,
      type: 'function',
      gas: 715,
    },
    {
      name: 'getToken',
      outputs: [{ type: 'address', name: 'out' }],
      inputs: [{ type: 'address', name: 'exchange' }],
      constant: true,
      payable: false,
      type: 'function',
      gas: 745,
    },
    {
      name: 'getTokenWithId',
      outputs: [{ type: 'address', name: 'out' }],
      inputs: [{ type: 'uint256', name: 'token_id' }],
      constant: true,
      payable: false,
      type: 'function',
      gas: 736,
    },
    {
      name: 'exchangeTemplate',
      outputs: [{ type: 'address', name: 'out' }],
      inputs: [],
      constant: true,
      payable: false,
      type: 'function',
      gas: 633,
    },
    {
      name: 'tokenCount',
      outputs: [{ type: 'uint256', name: 'out' }],
      inputs: [],
      constant: true,
      payable: false,
      type: 'function',
      gas: 663,
    },
  ],
};
